---
  language: go
  sudo: required
  notifications:
    email: false
  go:
    - 1.7
  script: make deps .gitvalidation validate test test-skopeo
  dist: trusty
  os:
    - linux
  addons:
    apt:
      packages:
        - btrfs-tools
        - libdevmapper-dev
        - libgpgme11-dev
