---
  language: go
  sudo: required
  notifications:
    email: false
  go:
    - 1.6.2
  install: make deps
  script: make validate && make test
  dist: trusty
  os:
    - linux
  addons:
    apt:
      packages:
        - libgpgme11-dev
